import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { usePortalBase } from "../../lib/usePortalBase";
import { UserPlus, Eye, CheckCircle2 } from "lucide-react";
import Drawer from "../ui/Drawer";
import Button from "../ui/Button";
import { RiskBadge, StatusBadge } from "../ui/Badge";
import { ConfirmDialog } from "../ui/Feedback";
import type { RiskAlert } from "../../types";
import { updateAlertStatus } from "../../services/api";
import { useToast } from "../../context/ToastContext";

export default function AlertDetails({
  alert,
  onClose,
  onUpdated,
}: {
  alert: RiskAlert | null;
  onClose: () => void;
  onUpdated: (alert: RiskAlert) => void;
}) {
  const navigate = useNavigate();
  const portalBase = usePortalBase();
  const { showToast } = useToast();
  const [confirmAction, setConfirmAction] = useState<null | "resolve" | "review" | "assign">(null);
  const [loading, setLoading] = useState(false);

  if (!alert) return null;

  async function runAction(status: RiskAlert["status"], message: string) {
    setLoading(true);
    try {
      await updateAlertStatus(alert!.id, status);
      const updated: RiskAlert = { ...alert!, status };
      onUpdated(updated);
      showToast(message, "success");
    } catch (err: any) {
      showToast(err?.message || "Failed to update alert", "error");
    } finally {
      setLoading(false);
      setConfirmAction(null);
    }
  }

  return (
    <>
      <Drawer open={!!alert} onClose={onClose} title={`Alert ${alert.id}`}>
        <div className="space-y-5">
          <div className="flex items-center gap-3">
            <span className="text-3xl font-bold text-gray-900">{alert.riskScore}</span>
            <RiskBadge level={alert.riskLevel} />
            <StatusBadge status={alert.status} />
          </div>

          <div>
            <p className="text-xs text-gray-400">Project</p>
            <button
              onClick={() => navigate(`${portalBase}/projects/${alert.projectId}`)}
              className="text-sm font-medium text-navy-700 hover:underline"
            >
              {alert.projectId} — {alert.projectName}
            </button>
            <p className="text-xs text-gray-500 mt-0.5">{alert.location}</p>
          </div>

          <div>
            <p className="text-xs text-gray-400">Alert Type</p>
            <p className="text-sm text-gray-800 mt-0.5">{alert.type}</p>
          </div>

          <div>
            <p className="text-xs text-gray-400">Reason</p>
            <p className="text-sm text-gray-700 mt-0.5 leading-relaxed">{alert.description}</p>
          </div>

          <div>
            <p className="text-xs text-gray-400">Evidence</p>
            <div className="flex flex-wrap gap-1.5 mt-1.5">
              {alert.evidence.length ? (
                alert.evidence.map((e) => (
                  <span key={e} className="text-xs bg-gray-100 text-gray-600 px-2.5 py-1 rounded-full">
                    {e}
                  </span>
                ))
              ) : (
                <span className="text-xs text-gray-400">No linked evidence records.</span>
              )}
            </div>
          </div>

          <div className="bg-navy-50 border border-navy-100 rounded-lg p-3">
            <p className="text-xs font-semibold text-navy-800 mb-1">AI Explanation</p>
            <p className="text-xs text-navy-700 leading-relaxed">
              This alert was generated by the risk scoring engine based on aggregated cost, progress, and
              behavioural signals. It flags a pattern requiring verification — not a confirmed irregularity.
            </p>
          </div>

          <div>
            <p className="text-xs text-gray-400 mb-1">Recommended Action</p>
            <p className="text-sm text-gray-700">{alert.recommendedAction}</p>
          </div>

          <div className="pt-3 border-t border-gray-100 flex flex-col gap-2">
            <Button variant="outline" icon={<UserPlus size={14} />} onClick={() => setConfirmAction("assign")}>
              Assign Officer
            </Button>
            <Button variant="outline" icon={<Eye size={14} />} onClick={() => setConfirmAction("review")}>
              Mark Under Review
            </Button>
            <Button variant="primary" icon={<CheckCircle2 size={14} />} onClick={() => setConfirmAction("resolve")}>
              Resolve Alert
            </Button>
          </div>
        </div>
      </Drawer>

      <ConfirmDialog
        open={confirmAction === "resolve"}
        onClose={() => setConfirmAction(null)}
        onConfirm={() => runAction("Resolved", `Alert ${alert.id} marked as resolved.`)}
        title="Resolve this alert?"
        description="This will mark the alert as resolved. This action can be reversed later if needed."
        confirmLabel="Resolve"
        loading={loading}
      />
      <ConfirmDialog
        open={confirmAction === "review"}
        onClose={() => setConfirmAction(null)}
        onConfirm={() => runAction("Under Review", `Alert ${alert.id} marked under review.`)}
        title="Mark as Under Review?"
        description="This will flag the alert as currently under officer review."
        confirmLabel="Mark Under Review"
        loading={loading}
      />
      <ConfirmDialog
        open={confirmAction === "assign"}
        onClose={() => setConfirmAction(null)}
        onConfirm={() => runAction("Assigned", `Alert ${alert.id} assigned to an officer.`)}
        title="Assign this alert?"
        description="This will assign the alert to the field verification officer for on-ground inspection."
        confirmLabel="Assign"
        loading={loading}
      />
    </>
  );
}
